### ISSUE TITLE
Controls repositioned

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/PEMEditor#1]
Great tool, but...
Open form for modification and select a control.
Make a change to a method of the control.
Use the PEM drop down to list and select the form.
Labels and shapes' LEFT positions are set to 0 .

Positions remain 'as is' if I click on the form to select it.

**Comment by DougHennig** [comment]
I can't reproduce that. Here are the steps I took:

- Opened PEM Editor
- MODIFY FORM MyForm
- Selected a control from the PEM Editor dropdown
- Double-clicking the Click method in the PEM Editor to open the editor for that method, made a change, and hit Ctrl+W to save and close
- Selected the form from the PEM Editor dropdown

I don't see any change in the positions of any controls.

**Comment by BobWilkes** [comment]
TNX, Doug.
UNCLE! I tried to set up a test form and, of course, no problem there. Arrgh! Obviously, issue is tied to some particular circumstance on a given form. I've had it happen a couple of times i the past, but don't remember if it was on the same form or not. Will TABLE the issue for now and see if I can recreate.
