### ISSUE TITLE
Install issue during install "Data Type Mismatch... 

### ISSUE THREAD

**Issue by parios59** [VFPX/PEMEditor#12]
code errors out, please see attached.

![PemeEditorInstallError](https://user-images.githubusercontent.com/8902122/160616440-4fa3dc7c-d930-46c7-8c2f-e277311fd194.png)

thx
parios59@gmail.com

**Comment by DougHennig** [comment]
We're doing some maintenance on PEMEditor right now. I'll let you know when it's ready.

**Comment by DougHennig** [comment]
This should be fixed now.

**Comment by parios59** [comment]
Great as usual, Thx Doug!!!!

**Comment by parios59** [comment]
hey Doug,
   is there a document on doing a clean install of thor...?

thx...

Pete Rios
***@***.***
***@***.*** ***@***.***>*
760-455-9461
