### ISSUE TITLE
Problem get the update to work

### ISSUE THREAD

**Issue by lscheffler** [VFPX/PEMEditor#15]
@DougHennig, I have a problem.   
It's still not working. I see where, but not how to fix.

- I have a clone of https://github.com/VFPX/PEMEditor on my comp
- I alter in that directory the code that creates PEMEditor.app
- To debug/test I copy that to .\Thor\Thor\Thor\Tools\Apps\PEM Editor\PEMEditor.app

To publish I copy this app and the sources into PEMEditor_Source.zip and push.

---
Now the problem
in PEME_Main.Init OF .\source\PEMEditor_Main.VCX
there is code
```
lcMyPath		  = .ClassLibrary
.cApplicationPath = Addbs (Justpath (Justpath (lcMyPath)))
```
The problem is on my test `.ClassLibrary` returns the path of the source code folder from above, something like
_.\PEMEditor\downloads\Source\PEMEditor_Main.VCX_   
.cApplicationPath goes to _.\PEMEditor\downloads\_     

The app downloaded returns _.\thor\thor\thor\tools\apps\pem editor\peme_utils.vcx_   for classlib - that is the location of the app, the library itself is in _.\thor\thor\thor\tools\apps\pem editor\source_
.cApplicationPath goes to  _.\thor\thor\thor\tools\apps\_.     
The problem comes in `PEMEditor_Utils.init OF Source\PEME_Utils.VCX`
```
	.oBeautifyX 	 = Newobject ('Beautify', 			'Source\PEME_Beautify.VCX', 		''	;
		  , This, .oPrefs, .oEditorWin, Filetostr (.cApplicationPath + 'Tables\SystemMemoryVariables.txt'))
```
The file `'Tables\SystemMemoryVariables.txt'` is found on my test, because it is in
_.\PEMEditor\downloads\Tables\SystemMemoryVariables.txt_   
but the version downloaded with Thor looks into _.\thor\thor\thor\tools\apps\Tables\SystemMemoryVariables.txt_   This fails because
the file is in _.\thor\thor\thor\tools\apps\pem editor\Tables\SystemMemoryVariables.txt_   

So I have no idea how to compile the app in a way that it finds the classlib in the source folder of thor, that is a relative path to the vcx.

I, myself, would try to do the stuff relative to the app and not the classlib compiled into, but I see not if there are other problems.

**Comment by lscheffler** [comment]
@Doug, I think I found a solution.    
It's the place where the app is compiled to. It must not be compiled to _.\PEMEditor\downloads\Source\PEMEditor.app_ but to _.\PEMEditor\downloads\PEMEditor.app_ so the relative path will be included to the app.

I will push later on this day.

**Comment by DougHennig** [comment]
This may be the same issue you are running into, but I updated to the latest PEMEditor and am getting an error on that same line:

```
.oBeautifyX 	 = Newobject ('Beautify', 			'Source\PEME_Beautify.VCX', 		''	;
		  , This, .oPrefs, .oEditorWin, Filetostr (.cApplicationPath + 'Tables\SystemMemoryVariables.txt'))
```

The issue is that the current folder is some place on my machine other than where Thor (or PEMEditor) is located, so "Source\PEME_Beautify.vcx" does not exist.

What I don't understand is the previous line:

```
.oServer		 = Newobject ('PEMEditor_Server', 	'Source\PEME_Server.PRG', '')
```

How does it find Source\PEME_Server.PRG? And if it can find that, why doesn't it find Source\PEME_Beautify.VCX?

Anyway, I think there are a couple of things that need fixing:

1. In PEMEditor_Main.Init, this line:

```
.cApplicationPath = Addbs (Justpath (Justpath (lcMyPath)))
```

results in .cApplicationPath being one folder higher than it should be. Perhaps it should be:

```
.cApplicationPath = Addbs (Justpath (lcMyPath))
```

2. The code instantiating objects in PEMEditor_Utils.Init uses "Source\" as the folder for the files. I think that should have .cApplicationPath in front of it, such as:

```
.oServer		 = Newobject ('PEMEditor_Server', 	.cApplicationPath + 'Source\PEME_Server.PRG', ''

**Comment by lscheffler** [comment]
@Doug Digging into it, may state of the mind as of now.   
The App is located on level down from the pjx _.\thor\thor\thor\tools\apps\pem editor\source_ to the _.\thor\thor\thor\tools\apps\pem editor_ folder and it looks like this is done by selecting this folder while compiling. VFP, while compiling sets relative paths to the vcx's for what ever reason, for example debug.    

If one (as I have done) compile to a different folder and copy the app, the path is relative to this. 

So the trick is to compile the app **one level down of the pjx** then the VCX is relativ to ther app in _.\source\_   
Since I'm afraid that if we do as you suggest, we might create problems in an other part, I would stuck to this kludge.  I guess we give it a try, I will push in couple of minutes.

**Comment by lscheffler** [comment]
@DougHennig I created a pull request.   

It my comp it works if I
- compile from my source one level down, copy to  Thor and rename my source so that is not available or
- compile the PJX in Thor one level down    

So this should work now. I try to create a contribute file ...
