### ISSUE TITLE
Control selector causes contained controls to Left=0

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/PEMEditor#2]
OK, Doug. I think I've got a sample for you to work with. Results are consistent on my box.
Open kcntProgBar in the enclosed Test.vcx
Note that this container has three controls:
	1. shpBar Dark Blue "thermometer bar"
		Starting pos Left 2
	2. shpBarBG	Gray background, Black border
	3. txtBarPercent centered across contaoiner width

1. With the mouse, select shpBar.
2. In the PEMEditor, drop down the controls selector and select the container.

On my system at least, this triggers the "evil processor" method.
All controls slam to the left and there seems to be an endless loop in progress.
Happy hunting,
Bob

[ControlPos.zip](https://github.com/VFPX/PEMEditor/files/1679965/ControlPos.zip)

**Comment by DougHennig** [comment]
Thanks: that helped me track down the bug. Fixed in the latest release.
