### ISSUE TITLE
PEM Editor w/o using THOR

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/PEMEditor#26]
## ℹ Computer information

- VFP version:  09.00.0000.7423
- PEMEditor version: Version 7.41.01 Released 2022-04-07
- Last PEMEditor version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. …try running the APP PEMEditor.APP. It gives an error about _Screen.cThorDispatcher no existing
2. …It does create the program StartPEMEditor.PRG
3. …When I try to run StartPEMEditor.prg it gives the same error about _Screen.cThorDispatcher.

### ✔️ Expected result

_What is the expected result of the above steps?_

I cannot find anything in the documentation that says that you have to be running THOR to use this utility, yet it seems to constantly give you errors if you are NOT using THOR.

### ❌ Actual result

_What is the actual result of the above steps?_

---
_Any of the sections following might be removed if unused_

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_   

## Hints

_Any usefull hints how to deal with the problem?_

**Comment by CHamlinPNP** [comment]
It has been a couple of weeks with nobody responding. I tried this again by downloading a pristine copy of the program again, ran the PEMEditor.app which created StartPEMEditor. When I run it (once again, this is an entirely unmodified program straight from VFPx) and it gives the error as shown. It appears to be on line 36 of editproperty. Any ideas why I cannot get the virgin program to run out of the "box". Please get back to me.
![2022-04-29_15-03-21](https://user-images.githubusercontent.com/34104227/166009765-2af3d42c-0e48-48fc-89ce-f036326eab9e.png)
![2022-04-29_14-58-50](https://user-images.githubusercontent.com/34104227/166009769-068e5ee2-a946-401a-9af8-382da25f8af7.png)

**Comment by rschummer** [comment]
Documentation might not state the dependency on Thor, but the code and your reported error indicate that there is a dependency. Given both tools were written by Jim Nelson, it seems likely that he incorporated at least one line of code that is dependent. Thor does not really have a high overhead cost to the IDE, and so many benefits.

**Comment by tbleken** [comment]
PEMEditor can't run on its own. It's a part of Thor and must be run from Thor.
