### ISSUE TITLE
question to latest change

### ISSUE THREAD

**Issue by lscheffler** [VFPX/PEMEditor#27]
Hi @DougHennig 

Would you mind to  create the vc2 file to your latest change and push it ?

I need to check that `nAlignASBlockMax`  is doing as expected. I changed something nearby - basically to use 0 to say _no maximum_.

The vc2 makes trace of changes much more easy. :)

Thanks

Edit: This is the value `nAsColumn` from the interface, that allows 0 as _no maximum_.   
See [here](https://github.com/VFPX/PEMEditor/blob/master/Documentation/pemeditor_thor_changes_7_40.md) under _ALIGN AS_

**Comment by lscheffler** [comment]
@DougHennig 
I was able to check it, looks like all works as expected. Somehow I have `SELECT  .. AS .. FROM` all the time, so I never run into this ...   
Anyway, please push the vc2

**Comment by DougHennig** [comment]
Done.

Doug
