### ISSUE TITLE
Problem with not closed TEXT .. ENDTEXT

### ISSUE THREAD

**Issue by lscheffler** [VFPX/PEMEditor#28]
## ℹ Computer information

- VFP version: VFPA
- PEMEditor version: 7.41.02
- Last PEMEditor version w/o bug (if available): n/a

## 📝 Provide detailed reproduction steps (if any)

1. Allow BeautifyX to create LOCALS
2. Create a program snippet like
```
 TEXT TO m.lcReturn TEXTMERGE NOSHOW
 SELECT
 xxx
 FROM <<m.tcTable>>
 into cursor curCURSOR
 WHERE xx
```
3. Run BeautifyX

### ✔️ Expected result

Should run and create `LOCAL lcReturn`.

### ❌ Actual result

Fails with _Array dimensions are invalid (Error 230)_ in `Beautify.DoLocals`, line 80 called out of `Beautify.CreateLocalsForCodeBlock`.
This is because of the missing `ENDTEXT` clause. 

---

## Note

This issue is for completeness, I will look up the error later on.

**Comment by lscheffler** [comment]
#### Ideas 
What should happen:   
At least do not crash, Messagebox if EOF is found, possibly.   
What happens if ENDTEXT is found some procedures below? Like
```
TEXT TO xx
......

ENDFUNC

FUNCTION lal

TEXT TO YYY
....
ENDTEXT?

```

**Comment by lscheffler** [comment]
Problem happens, as expected, with _Create Locals_ too.

**Comment by lscheffler** [comment]
As far as the code looks, this will happen to `#IF .. #ENDIF` with blocks missing `#ENDIF` too.

**Comment by lscheffler** [comment]
Something on the update did not work as expected. Error is still there.   
@DougHennig  please reopen the issue.

**Comment by DougHennig** [comment]
Done

**Comment by lscheffler** [comment]
Now it works.
