### ISSUE TITLE
PEM Editor Zip corrupt

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/PEMEditor#3]
Thor just tried to update PEM Editor - Greeat!
It failed: Update 7.30
"Error in packed file" (pem editor - 7.30.00 - january 31, 2018 - 20150131.zip)
Something's amiss. Project list shows latest PEM Editor Ver as 7.20 2012/08/19
(Neither versions nor dates match)

**Comment by DougHennig** [comment]
Fixed: I forgot GitHub is case-sensitive for file paths.
