### ISSUE TITLE
Case of Method/Property names incorrect

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/PEMEditor#31]
## ℹ Computer information

- VFP version: 9
- PEMEditor version: 7.41.03
- Last PEMEditor version w/o bug (if available): unk...it's been that way for some time.

## 📝 Provide detailed reproduction steps (if any)
Not a big deal but...
If I open one class in PEM Editor, Case of method & property names is as specified by display entry in _MemberData, e.g., ClearError.
If I open a second class, it's entries are also AOK.
When I close one, the inherited names of the remaining class are displayed in lower case.
NBD. If I close and reopen the class, all is restored.

**Comment by DougHennig** [comment]
I can't reproduce that. Can you give a set of exact steps including screen shots?

**Comment by BobWilkes** [comment]
>I can't reproduce that. Can you give a set of exact steps including 
>screen shots?
>
>Message ID: ***@***.***>Why, tes, I 
>can!
>


>
>

Let me know if you need anything else. Have fun!

**Comment by DougHennig** [comment]
There was no attachment to your message.

**Comment by BobWilkes** [comment]
Step one
![Step1](https://user-images.githubusercontent.com/34778960/188738374-f9b7783a-be59-405a-a759-00fcd748212b.jpg)
Step two
![Step2](https://user-images.githubusercontent.com/34778960/188738415-c0b25cf3-1975-4ff4-b6e2-df6957fea4d2.jpg)
Step three
![Step3](https://user-images.githubusercontent.com/34778960/188738453-4b5a7af2-1c84-4a7b-9e61-fd8c52fc2321.jpg)

**Comment by DougHennig** [comment]
Sorry, Bob: I can see from the screen shots that it's happening for you but I can't reproduce that. My classes also have an About method and following your steps I see the first class still has it capitalized after I close the second.

**Comment by BobWilkes** [comment]
OK! Guess I'm special! 😁
No big deal, as all is well after I close and reopen.
Guess you can close this out as Non-reproducable, inconsequencial.
