### ISSUE TITLE
Properties with name length > 60 cannot be edited

### ISSUE THREAD

**Issue by SGajinovic** [VFPX/PEMEditor#32]
## ℹ Computer information

- VFP version: 9 
- PEMEditor version: 7.41.03
- Last PEMEditor version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. Initially, it is possible with PEMEditor to add property with name length > 60 (i.e. : ***Invoice_AccountingSupplierParty_Party_PostalAddress_Country_IdentificationCode***, with length of 78). PEMEditor correctly add that property also with MemberData
2. After that, first left column at PEMEditor displays new property name cut at max. 60 characters (in this example: ***Invoice_AccountingSupplierParty_Party_PostalAddress_Country_*** ). However, VFP properties window displays correctly whole long name (I think that VFP's limit is 128 characters (?!))
3. Apart of displaying issue, this property cannot be changed later with PEMEditor (Name, Default value or Description). Instead of those changes, VFP will (or will try to) create new property with name shortened to 60 characters (***Invoice_AccountingSupplierParty_Party_PostalAddress_Country_*** ).

### ✔️ Expected result

PEMEditor should handle property names longer than 60 characters.

### ❌ Actual result

PEMEditor can create properties with names longer than 60 chracters, but cannot edit them later.

---

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/33139275/197993382-ba93b072-f250-4944-a9c3-f8598cc377ee.png)

**Comment by DougHennig** [comment]
This issue is fixed in version 7.41.05.
