### ISSUE TITLE
List of local variabels

### ISSUE THREAD

**Issue by KuceraJanSupport** [VFPX/PEMEditor#33]
## ℹ Computer information

- VFP version: 9
- PEMEditor version: 7.41.05
- Last PEMEditor version w/o bug (if available):

1. Calling up the list of local variables via CTRL+SPACE works. A warning message will appear, and after ignoring it twice, a list of variables will appear again.

### ✔️ Expected result

No error message

### ❌ Actual result

Error message

## 📷 Screenshots
![obrazek](https://user-images.githubusercontent.com/30229034/199455635-b9dbd579-dff3-41cc-b5fa-30f2206d10ff.png)
![obrazek](https://user-images.githubusercontent.com/30229034/199455774-903c16eb-c227-4a28-9985-08d6c741c1fc.png)

**Comment by mikepotjer** [comment]
I'm seeing the same issue after installing this update.

**Comment by DougHennig** [comment]
This is fixed in the latest build.

**Comment by mikepotjer** [comment]
Thanks @DougHennig, it's behaving as expected now.
