### ISSUE TITLE
ThorUpdater not working

### ISSUE THREAD

**Issue by JoelLeach** [VFPX/PEMEditor#34]
I tried to install the PEM Editor 7.41.06 using ThorUpdate, but it fails.  I think it's because [downloads/ThorUpdater/PEMEditor_Source.zip](https://github.com/VFPX/PEMEditor/commit/eb4d4adda8acf6b1b069418a76e02b2f2e7edacc#diff-34943a3c4a8fa33694d9961d72635a2e74f292854a5e3edbe7ac72b434e9a5da) was removed in a recent commit, but I'm not certain.

**Comment by DougHennig** [comment]
Fixed.
