### ISSUE TITLE
Option to NOT display splash screen on startup

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/PEMEditor#36]
Hey, Doug. Just updated to v 7.41.07 and I'm now getting the splash screen on every startup of PEMEd,
which I do frequently during development...
I was hoping there was an option to suppress this 'feature' but I don't see it.
Could you add that, pls?
Perhaps on the Prefs, Startup screen.

And now, after several startups, it's not displaying...which begs the question, "Why was it being displayed / Why did it stop?"
TIA,
Bob W.

**Comment by DougHennig** [comment]
I think this was a deployment issue from Jim Nelson's latest changes, and I believe he fixed that.
