### ISSUE TITLE
Method(s) in PEMEditor fail checking for baseclass when called with objects based on [Empty]

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/PEMEditor#37]
This problem is actually experienced in IntellisenseX which makes use of classes in PEM Editor.

With IntellisenseX active:
1.  loEmpty = CreateObject('Empty')
2.  AddProperty(loEmpty, 'AnyName')
3.  loEmpty{DOT}

This gives the error 'Property BASECLASS not found' on this line of code:
      llActiveX = Lower(.oObject.BaseClass) = 'olecontrol'

The line should be replaced with:
      llActiveX = Pemstatus(.oObject, 'BaseClass', 5) and (.oObject.BaseClass) = 'olecontrol'

There are multiple instances of this code and they should all be fixed.

**Comment by DougHennig** [comment]
I'll look in to that this weekend.

**Comment by DougHennig** [comment]
Fixed in the latest release.
