### ISSUE TITLE
Web Page Links broken

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/PEMEditor#4]
Broken links on page:	https://github.com/VFPX/PEMEditor#WhatsNew

In PEM Editor 7 section
1. Text:	'What's new in this release'
   Link:	https://github.com/VFPX/PEMEditor#WhatsNew
   	Is a cyclical link to the current page.

2. Text:	'Click here for complete online documentation of IDE Tools'
   Link:	https://github.com/VFPX/PEMEditor/blob/master/PEM%20Editor%20IDE%20Tools%20Help.html
		Can't find page

3. Text:	'One-Click Update of Thor'
   Link:	https://github/VFPX/Thor
   		Can't find server

4. Text:	'Setting ControlSources in PEM Editor'
   Link:	https://github.com/VFPX/IntelliSenseX/Thor%20IntellisenseX%20ControlSources.html
   		Can't find page

Version 7.1: What's new in this release, Objects published by PEM Editor section 
5. Both 'EditorWindow Object' and 'Tools Object' links are broken (404 error)

**Comment by DougHennig** [comment]
Fixed.
