### ISSUE TITLE
When closed, PEMeditor does not clean up well

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/PEMEditor#46]
This item is a continuation of [https://github.com/VFPX/Thor/issues/122]

PEMEditor does a remarkably poor job of closing all its sub-objects when it closes.  (I really did not know how to handle it properly when I created it).

For one thing, as you can see from the following image from Object Explorer, we have recursive definitions of objects within the public variable _oPemEditor_.  Look at _oUtils_ and the objects it contains, many of which contain _oUtils_.  Plenty of examples of this.

![image](https://github.com/VFPX/PEMEditor/assets/81179335/eeac6a7b-8e95-4b8c-b74f-98929acbb8fe)

The effect of this, I believe, is that when _oPEMEditor_ is released, some of the sub-objects do not clean up properly.  That is why the folder referred to in the Thor issue is still in use.

I am only noting this so that there is awareness, not that I would expect anybody to undo the mess.

**Comment by lscheffler** [comment]
You might assign it to yourself.  Top right *Assignees * on this page.or ask Doug. :)

The oUtils looks like a try to access it from within the whatever object like *oIDEx* with THIS rather then via a magic external variable, this was state of the art one time. From me working on PEMEditor I thought this was local instance of the oUtils, so it was fine to me. I never checked if this is a general object referenced.

**Comment by Jimrnelson** [comment]
Oh, I'm not volunteering to fix this.  It's a mess and I can't see the benefit to investing the time in it.
