### ISSUE TITLE
Problem renaming properties/methods using 7.41.12

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/PEMEditor#50]
## ℹ Computer information

- VFP version: 9
- PEMEditor version: 7.41.12
- Last PEMEditor version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. …Open a form
2. …Using PEMEditor...rename the name of the property/method
3. …Click save and get an error

### ✔️ Expected result

_What is the expected result of the above steps?_Expected results that it would be properly renamed and all necessary internal tables would update

### ❌ Actual result

_What is the actual result of the above steps?_Instead what happens is that you receive an error that CLSADDWORDSTOCKL class definition does not exist. It appears that the line "loAddWordstoCKL = Execscript(_Screen.cThorDispatcher, 'Class= clsAddWordstoCKL from Thor_Proc_AddWordsToCKL.PRG')" fails and therefore you get the error. I have checked my Thor repository and cannot find the file that it is looking for.

I have reinstalled PEM but it has done nothing to alleviate this issue.

---
_Any of the sections following might be removed if unused_

## 📷 Screenshots

https://github.com/VFPX/PEMEditor/assets/34104227/af73bc7d-3ce2-4794-8f59-cb1d2545438f

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_ Have added a short video to show the error.  

## Hints

_Any usefull hints how to deal with the problem?_

**Comment by Jimrnelson** [comment]
This problem was fixed with a release of ThorRepository, 2023-08-29, Version 65.14

**Comment by Jimrnelson** [comment]
``
