### ISSUE TITLE
Availability of Pem or Gofish after starting Foxpro 9.0 

### ISSUE THREAD

**Issue by parios59** [VFPX/PEMEditor#51]
![2023-08-17_05-07-12](https://github.com/VFPX/PEMEditor/assets/8902122/77bde6c4-2d3e-4b93-9def-c4e6c349c9e6)

https://github.com/VFPX/PEMEditor/assets/8902122/72988d4d-1403-4caf-991c-f895759fc5bd

## ℹ Computer information

- VFP version: 9.0  7423
- PEMEditor version:
- Last PEMEditor version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. …starting vfp and every time after 
2. …Pem or Gofish is not available until update is done on Thor
3. …After thor is done checking for updates it show the options to start Pem Or Gofish

### ✔️ Expected result  : able to fire gofish or pem

_What is the expected result of the above steps? 

### ❌ Actual result   no option to fire the pem editor or gofish

_What is the actual result of the above steps?_

---
_Any of the sections following might be removed if unused_

## 📷 ![2023-08-17_05-07-12](https://github.com/VFPX/PEMEditor/assets/8902122/4856b18e-a8d9-44ab-9434-feec4f0136e3)

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_   

## Hints

_Any usefull hints how to deal with the problem?_  not sure please video

**Comment by Jimrnelson** [comment]
@parios59 

Do you start Thor by using RunThor or by calling Thor.App with parameters?

**Comment by parios59** [comment]
Thor.appSent from my iPhone, Please excuse my brevity.On Sep 22, 2023, at 04:13, Jimrnelson ***@***.***> wrote:﻿
@parios59
Do you start Thor by using RunThor or by calling Thor.App with parameters?

**Comment by Jimrnelson** [comment]
@parios59 

What is the code you use to call Thor.App?

**Comment by parios59** [comment]
Startup in the foxpro start up appSent from my iPhone, Please excuse my brevity.On Sep 22, 2023, at 13:50, Jimrnelson ***@***.***> wrote:﻿
@parios59
What is the code you use to call Thor.App?

**Comment by Jimrnelson** [comment]
@Jimrnelson 

Please show me the code you use to call Thor.App.  I need to see the code to understand what is going on.

**Comment by Jimrnelson** [comment]
@parios59 

Please show me the code you use to call Thor.App. I need to see the code to understand what is going on.

**Comment by parios59** [comment]
[image: image.png]


Pete Rios
***@***.***
***@***.*** ***@***.***>*
760-455-9461

**Comment by Jimrnelson** [comment]
Unfortunately, I can't see that image.  All I see is the following text:  [image: image.png]

Can you simply paste the code in?

**Comment by Jimrnelson** [comment]
@parios59 

Is this still an issue?

If so, can you paste in the code where you call Thor?

**Comment by Jimrnelson** [comment]
@parios59 

I am marking this item as complete; please re-visit if you still have a problem.

**Comment by parios59** [comment]
Thank you

 

 

Pete Rios

El Toro Export, LLC

Dev./IS/IT Mgr.

Office (760) 352-4157

Fax (760) 352-5754

Cell (760) 455-9461

***@***.*** ***@***.***> 

***@***.*** ***@***.***> 

 “Program to an interface, not in implementation!”

- Nick Hodges

P Please consider the environment before printing this e-mail

CONFIDENTIALITY NOTICE: This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.
