### ISSUE TITLE
Remove link to old Codeplex VFPx site from update dialog.

### ISSUE THREAD

**Issue by mattslay** [VFPX/PEMEditor#6]
After PEME is updated through Thor Check for Updates, the next time you run PEME, it pops up a dialog show the version number and some other info about PEME. On of the links on that dialog is to the old VFPx site on Codeplex. So, need to revise that link to point to the new GitHub page repo for PEME.

Here's a screenhot:

![2018-02-06_15-03-57](https://user-images.githubusercontent.com/309016/35944816-7dd6e566-0c23-11e8-9996-c206fd360156.png)

**Comment by DougHennig** [comment]
Fixed that and some other CodePlex links.
