### ISSUE TITLE
"Not an object file" error 

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/PEMEditor#7]
I think the latest release, 7.30.01, has broken some earlier fixes.
Was renaming an existing form method and got 'c:\...\vfp9\thor\tools\procs\thor_proc_managecustomkeywordlist.fxp is not an object' error.
The changed method name was saved but as all lower case. If I try to change it, I get the same error.
Additionaly, somewhere along the line, the (previously fixed) bug that resets all controls to left = 0 is back.

**Comment by DougHennig** [comment]
It turns out the resetting controls bug wasn't really fixed, but it is now in 7.30.02. As for the "not an object file" error, try deleting that FXP file.
