### ISSUE TITLE
Can't change method name

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/PEMEditor#8]
My version shows 7.30.02 - Feb 26, 2019, but that can't be correct.
Anyway, after latest update (via THOR) PEM Editor won't allow me to ADD a Method (Neither Alt-A nor click 'Save' do anything.)
Additionally, when I try to change the name of an existing method, Save issues:
c:\<Thor Path>\tools\procs\thor_proc_managecustomkeywordist.fxp is not an object file.
If I ignore that, it issues an "Unknown member OKEYWORDLIST" error, which I can ignore to effect the change.

**Comment by DougHennig** [comment]
I just tried adding and renaming a method and both work for me. Perhaps try deleting that FXP.
