### ISSUE TITLE
BeautifyX doesn't catch all arrays

### ISSUE THREAD

**Issue by billand88** [VFPX/PEMEditor#9]
Add the following code to a method:

= ALINES(laTest1, 1)

For li = 1 To ALINES(laTest2, 1)
Endfor

Then run the process that finds the missing locals. You will only catch one of the arrays. 
1) Apparently this is a problem with most or all of the "A" array functions (AMembers, APrinters, etc.)
2) The problem is - from someone who should know -- is the letter o before the ALines function. The LOCALs code does a CHRTRAN() and it should be a STRTAN(). Perhaps this: STRTRAN(" (", "( ")

**Comment by lscheffler** [comment]
Looks like this is open for a while. I just found the issue while publishing a new version.   
I think you localized it very close. The oddness is that one might have any number of space and tab between the word and the opening round bracket. Even line continuation(s).  In case of line continuation is inline comment possible. I need to think about how deep I like to go, anyway this is a problem better done with regexp.
